# Generated by Django 4.1.2 on 2024-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
