# Generated by Django 4.1.2 on 2024-01-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0004_bloodrequest_reasen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='unit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
