# Generated by Django 4.1.2 on 2024-01-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0005_remove_bloodrequest_status_bloodrequest_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='doctor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
