# Generated by Django 4.1.2 on 2024-01-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0006_bloodrequest_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
