# Generated by Django 4.1.2 on 2024-01-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0007_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
