# Generated by Django 5.0.1 on 2024-03-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_app', '0008_bloodrequest_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
